spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/sustc  # change this to your own jdbc url
    username: zwh  # change this to your own username (avoid using a superuser)
    password: haha  # change this to your own password

    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      connection-timeout: 30000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 0

logging:
  level:
    root: off
    io.sustc: debug

---

benchmark:
  data-path: data
  student-mode: true
